clone: 
  depth: 1
kind: pipeline
name: cooking
steps: 
  - 
    commands: 
      - "curl -s https://raw.githubusercontent.com/Rombuilding-X00TD/kernel_build_script-ci/main/build.sh | bash"
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
    image: panchajanya1999/archlinux:latest
    name: Build Kernel
    trigger: 
      branch: 
          - los
          - stock
