version: 2.1
jobs:
  compile:
   docker:
      - image: panchajanya1999/archlinux:latest
   steps:
      - run:
          command: |
            git clone --depth=1 https://github.com/Rombuilding-X00TD/android_kernel_asus_sdm660.git -b test kernel && cd kernel
            curl https://raw.githubusercontent.com/Rombuilding-X00TD/kernel_build_script-ci/main/build.sh > run.sh
            source run.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
